"""create auth_providers table

Revision ID: 21da739f9e9a
Revises: 2e260fd1f8f0
Create Date: 2026-01-01 16:31:34.724955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21da739f9e9a'
down_revision: Union[str, Sequence[str], None] = '2e260fd1f8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'DISCORD', 'DISCORD_BOT', name='providers'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_user', 'auth_providers', ['provider', 'provider_id'], unique=True)
    op.create_index(op.f('ix_auth_providers_id'), 'auth_providers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_providers_id'), table_name='auth_providers')
    op.drop_index('idx_provider_user', table_name='auth_providers')
    op.drop_table('auth_providers')
    # ### end Alembic commands ###
