"""add relationships between models

Revision ID: 7d81dbacd133
Revises: 21da739f9e9a
Create Date: 2026-01-01 17:01:34.827919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d81dbacd133'
down_revision: Union[str, Sequence[str], None] = '21da739f9e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_providers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('auth_providers', sa.Column('provider_user_id', sa.String(length=255), nullable=False))
    op.add_column('auth_providers', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('auth_providers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auth_providers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_provider_user', table_name='auth_providers')
    op.create_index('idx_provider_user_unique', 'auth_providers', ['provider', 'provider_user_id'], unique=True)
    op.create_index('idx_user_providers', 'auth_providers', ['user_id'], unique=False)
    op.create_foreign_key(None, 'auth_providers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('auth_providers', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_providers', sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'auth_providers', type_='foreignkey')
    op.drop_index('idx_user_providers', table_name='auth_providers')
    op.drop_index('idx_provider_user_unique', table_name='auth_providers')
    op.create_index('idx_provider_user', 'auth_providers', ['provider', 'provider_id'], unique=False)
    op.drop_column('auth_providers', 'updated_at')
    op.drop_column('auth_providers', 'created_at')
    op.drop_column('auth_providers', 'token_expires_at')
    op.drop_column('auth_providers', 'provider_user_id')
    op.drop_column('auth_providers', 'user_id')
    # ### end Alembic commands ###
