"""create habit cycle table

Revision ID: 8041d7dca206
Revises: 5a4db857cc4e
Create Date: 2026-01-01 15:51:15.942951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8041d7dca206'
down_revision: Union[str, Sequence[str], None] = '5a4db857cc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cycle_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='cycletypes'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ABANDONED', name='cyclestatuses'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_one_active_cycle_per_type', 'habit_cycles', ['user_id', 'cycle_type'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index(op.f('ix_habit_cycles_id'), 'habit_cycles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habit_cycles_id'), table_name='habit_cycles')
    op.drop_index('idx_one_active_cycle_per_type', table_name='habit_cycles', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('habit_cycles')
    # ### end Alembic commands ###
