"""add habit and habit entry tables

Revision ID: 8b99df995ff8
Revises: 7d81dbacd133
Create Date: 2026-01-02 21:35:23.257667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b99df995ff8'
down_revision: Union[str, Sequence[str], None] = '7d81dbacd133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_cycle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['habit_cycle_id'], ['habit_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_cycle_id', 'name', name='uniq_habit_per_cycle')
    )
    op.create_index(op.f('ix_habits_habit_cycle_id'), 'habits', ['habit_cycle_id'], unique=False)
    op.create_index(op.f('ix_habits_id'), 'habits', ['id'], unique=False)
    op.create_table('habit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'entry_date', name='uniq_habit_entry_date')
    )
    op.create_index(op.f('ix_habit_entries_entry_date'), 'habit_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_habit_entries_id'), 'habit_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habit_entries_id'), table_name='habit_entries')
    op.drop_index(op.f('ix_habit_entries_entry_date'), table_name='habit_entries')
    op.drop_table('habit_entries')
    op.drop_index(op.f('ix_habits_id'), table_name='habits')
    op.drop_index(op.f('ix_habits_habit_cycle_id'), table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
