"""update models

Revision ID: bb68846c25a3
Revises: 8b99df995ff8
Create Date: 2026-01-05 18:45:44.486250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb68846c25a3'
down_revision: Union[str, Sequence[str], None] = '8b99df995ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_cycles', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('habits', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'updated_at')
    op.drop_column('habit_cycles', 'updated_at')
    # ### end Alembic commands ###
